In [1]:
import pandas as pd
import os
import time
import numpy as np

In [2]:
os.chdir(r"C:\Users\Sidrcs\Downloads\SPSS_Processed\UKDA-5151-spss\spss\spss19")

In [3]:
df_residence = pd.read_csv(r"C:\Users\Sidrcs\Downloads\SPSS_Processed\UKDA-5151-spss\spss\spss19\bhps_w1\aindresp.csv")

C:\Users\Sidrcs\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3444: DtypeWarning: Columns (3,5,6,16,550,551,789,790,792,793) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

### Interested variables for visualization
Look for <code>aindresp.csv</code>. Required variables are: (These are columns names and their corresponding interpretation) <ul><li><code>aopsocc</code> : "Private enterprise is the best way to solve Britain’s economic problems" (S1)</li> <li><code>aopsocd</code> : "Major public services and industries ought to be in state ownership" (S2)</li> <li><code>aopsoce</code> : "It is the government’s responsibility to provide a job for everyone who wants one" (S3)</li> <li><code>afiyr</code> : <b>Self-reported annual income</b> </li> <li><code>afetype</code> : <b>Educational qualification</b></li> <li><code>aplbornc_cc</code> : <b>Country of birth</b></li> <li><code>aage12</code> : <b>Age</b></li> <li><code>ajbstatt</code> : <b>Employment status</b></li> <li><code>aplb4d</code> : <b>County Name</b> </li></ul>

In [4]:
# Loading variables of interest from 1991 BHPS dataset into dataframe
df_residence = df_residence[["aopsocc","aopsocd","aopsoce","afiyr","afetype","aage12","ajbstatt","aplb4d", "aplbornc_cc"]]

In [5]:
# Dropping rows if they donot have any spatial information
df_residence = df_residence[~df_residence["aplb4d"].isin(["don't know", "inapplicable", "missing or wild", "refused"])]

In [6]:
# To view columns
df_residence.head()

,aopsocc,aopsocd,aopsoce,afiyr,afetype,aage12,ajbstatt,aplb4d,aplbornc_cc
0,Agree,Not agree/disag,Disagree,3488.5703125,Other trng establmnt,91.0,Retired,City; Westminster,inapplicable
1,Agree,Not agree/disag,Not agree/disag,1789.7335205078125,University,28.0,Unemployed,Ealing,other country
2,Not agree/disagr,Strongly disagr,Strongly disagr,1789.7335205078125,University,26.0,Unemployed,Ealing,other country
3,Strongly disagr,Strongly disagr,Strongly disagr,7200.06005859375,None of the above,58.0,In paid employ,Brent,other country
4,Agree,Strongly disagr,Strongly disagr,12060.0,None of the above,54.0,Self employed,Hammersmith & Fulham,inapplicable

### Several measures are indirect analysis techniques are adopted from Grechyna (2022)
<ul>
    <li>The standard deviation of individual age in county-year</li>
    <li>The change in the fraction of natives among the respondent</li>
    <li>The variability of the highest educational qualifcation</li>
    <li>The variability of the job status in the county-year</li>
    <li>The fraction of employed full time</li>
    <li>Income inequality using Gini index for each county</li>
</ul>

In [7]:
# create an empty dataframe
output_df = pd.DataFrame()

# Group the dataframe by county and calculate standard deviation of age : "aage12"
output_df["std_dev_age"] = df_residence.groupby("aplb4d")["aage12"].agg("std")

# Group the dataframe by county and number of people born in UK : "aplbornc_cc"
output_df["born"] = df_residence.groupby("aplb4d")["aplbornc_cc"]

# Assuming inapplicable as people born in UK to all others
def native_share(x):
    pop_count = list(x["born"][1])
    native_count = pop_count.count("inapplicable")/len(pop_count)
    return native_count

# calculating fraction of natives in each county
output_df["native_share"] = output_df.apply(lambda x: native_share(x), axis = 1)

# Dropping "born" groupby column
output_df = output_df.drop(columns = ["born"], axis = 1)

# Creating afetype_dict based on PDF from 1991 BHPS data
afetype_dict = {"Nursing school etc" : 1, " College of f educ" : 2, " College of f educ" : 3, " Polytechnic" : 4, \
                "University" : 5, "None of the above" : 7, "don't know" : -1, "missing or wild" : -9, \
                    "inapplicable" : -8, "proxy" : -7, "refused" : -2}


# Create a new column "afetype_encoded" in the dataframe by replacing the values with encoded values from the dictionary
df_residence["afetype_encoded"] = df_residence["afetype"].replace(afetype_dict)

# Group the dataframe by county and "afetype_encoded"
output_df["education"] = df_residence.groupby("aplb4d")["afetype_encoded"]

# function to calculate dissimilarity in education
def dissimilarity_education(x):
    # loads tuple element into job
    job = x["education"][1]
    # loads frequency of each education type in county as list
    freq = list(job.value_counts())
    # calculates total number of groups
    s = len(freq)
    dissim_index = 0
    for i in freq:
        # formula of dissimilarity index
        dissim_index += 0.5 * abs(i-(1/s))
    return dissim_index

def county_name(x):
    return x["education"][0]

output_df["education_variability"] = output_df.apply(lambda x: dissimilarity_education(x), axis = 1)
output_df["county"] = output_df.apply(lambda x: county_name(x), axis = 1)

# Dropping "education" groupby column
output_df = output_df.drop(columns = ["education"], axis = 1)

# Creating ajbstatt_dict based on PDF from 1991 BHPS data
ajbstatt_dict = {"Self employed" : 1, "In paid employ" : 2, "Unemployed" : 3, "Retired" : 4, "Family care" : 5, \
                    "FT student" : 6,  "Long term sick/disabled" : 7, "On matern leave" : 8, \
                    "Govt trng scheme" : 9, "Something else" : 10, "don't know" : -1, "missing or wild" : -9, \
                    "inapplicable" : -8, "proxy" : -7, "refused" : -2}


# Create a new column "ajbstatt_encoded" in the dataframe by replacing the values with encoded values from the dictionary
df_residence["ajbstatt_encoded"] = df_residence["ajbstatt"].replace(ajbstatt_dict)

# Group the dataframe by county and calculate the mean and standard deviation of the encoded values
output_df["job"] = df_residence.groupby("aplb4d")["ajbstatt_encoded"]

# function to calculate dissimilarity in job
def dissimilarity_job(x):
    job = x["job"][1]
    freq = list(job.value_counts())
    s = len(freq)
    dissim_index = 0
    for i in freq:
        dissim_index += 0.5 * abs(i-(1/s))
    return dissim_index

# function to calculate fraction of employed people within each county
def frac_employed(x):
    job = list(x["job"][1])
    frac_emp = (job.count(2)/len(job))
    return frac_emp

output_df["job_variability"] = output_df.apply(lambda x: dissimilarity_job(x), axis = 1)
output_df ["frac_employed"] = output_df.apply(lambda x: frac_employed(x), axis = 1)

# Dropping "education" groupby column
output_df = output_df.drop(columns = ["job"], axis = 1)

# replacing all Not-A-Number cases to zero i.e., proxy values
df_residence["afiyr"] = df_residence["afiyr"].replace("proxy",0)

# Group the dataframe by county and calculate median based on self-reported annual income: "afiyr"
output_df["median_income"] = df_residence.groupby("aplb4d")["afiyr"].agg(["median"])

# convert "afiyr" column to float data type
df_residence["afiyr"] = df_residence["afiyr"].astype("float32")

# group incomes by county
output_df["income"] = df_residence.groupby("aplb4d")["afiyr"]

def gini_index(x):
    data = list(x["income"][1])
    # sort the data in ascending order
    sorted_data = np.sort(data)
    # calculate the cumulative sum of the sorted data
    cumsum_data = np.cumsum(sorted_data)
    # calculate the Lorenz curve values
    lorenz_curve = cumsum_data / cumsum_data[-1]
    # calculate the area under the Lorenz curve
    area_lorenz_curve = np.trapz(lorenz_curve, dx=1/len(data))
    # calculate the Gini index
    gini_index = 1 - 2 * area_lorenz_curve
    return gini_index

output_df["gini_index"] = output_df.apply(lambda x : gini_index(x), axis = 1)

# Drop "income" groupby column
output_df = output_df.drop(columns = ["income"], axis = 1)

output_df

,std_dev_age,native_share,education_variability,county,job_variability,frac_employed,median_income,gini_index
aplb4d,,,,,,,,
Aberdeen City,15.196623,0.875000,27.5,Aberdeen City,27.5,0.607143,5455.766113,0.519385
Adur; Worthing,21.108135,0.894737,18.5,Adur; Worthing,18.5,0.421053,5003.030029,0.470579
Allerdale; Carlisle,16.277886,0.963303,54.0,Allerdale; Carlisle,54.0,0.605505,6204.619629,0.442821
Alnwick; Berwick; Morpeth; Tynedale,23.060996,1.000000,3.0,Alnwick; Berwick; Morpeth; Tynedale,3.0,0.285714,3715.673340,0.377750
Alyn & Deeside; Delyn; Wrexham Maelor,17.071726,0.975610,61.0,Alyn & Deeside; Delyn; Wrexham Maelor,61.0,0.455285,5108.415039,0.424249
...,...,...,...,...,...,...,...,...
Wirral,19.975800,0.933333,52.0,Wirral,52.0,0.361905,4551.285156,0.563936
Wokingham,15.587291,1.000000,5.0,Wokingham,5.0,0.818182,10648.406250,0.278845
Wolverhampton,17.193862,0.923077,19.0,Wolverhampton,19.0,0.384615,3943.374512,0.465119
Woodspring,20.884911,0.962963,13.0,Woodspring,13.0,0.481481,12391.048828,0.395611
Wycombe,14.807123,0.911765,33.5,Wycombe,33.5,0.514706,8316.907227,0.530993

### Quantifying political polarization in the UK based on BHPS data (1991)
<ul>
    <li>Lindqvist and Östling (2010)</li>
    <li>Abramowitz and Saunders (2008) and Boxell et al. (2017)</li>
    <li> Esteban and Ray (1994) and Duca and Saving (2016) </li>
</ul>

In [8]:
# Define the dictionary to encode the "aopsocc" column which is Statement 1 (S1)
# S1: "Private enterprise is the best way to solve Britain’s economic problems."
aopsocc_dict = {"Agree":2, "Disagree":4 , "Not agree/disagr": 3 ,"Strongly disagr": 5, 
                "don't know": -1 , "Strongly agree": 1 ,"proxy":-7, "missing or wild": -9, 
                "refused":-2, "inapplicable":-9}

# Create a new column "aopsocc_encoded" in the dataframe by replacing the values with encoded values from the dictionary
df_residence["aopsocc_encoded"] = df_residence["aopsocc"].replace(aopsocc_dict)

# Political polarization measurement by Lindqvist and Ostling (2010)
output_df["Lindqvist_Ostling_S1"] = df_residence.groupby("aplb4d")["aopsocc_encoded"].agg(["var"])

# Create new columns based on absolute sum of encoded values of opinions and counts
output_df["abs_sum"] = df_residence.groupby("aplb4d")["aopsocc_encoded"].apply(lambda x: x.abs().sum())
output_df["counts"] = df_residence.groupby("aplb4d")["aopsocc_encoded"].apply(lambda x: x.count())

# Political polarization measurement by Abramowitz and Saunders (2008)
output_df["Abramowitz_Saunders_S1"] = output_df.apply(lambda x: x["abs_sum"]/x["counts"], axis = 1)

output_df = output_df.drop(columns = ["abs_sum", "counts"], axis = 1)

# Group the dataframe by county and aopsocc_encoded values
output_df["dkp"] = df_residence.groupby("aplb4d")["aopsocc_encoded"]

# Political polarization measurement by Duca and Saving (2016)
def duca_saving(x):
    county_tuple = x["dkp"]
    freq = list(county_tuple[1].value_counts())
    val = list(county_tuple[1].unique())
    norm_freq = [i/sum(freq) for i in freq]
    outer_sum = 0
    for i in range(len(norm_freq)):
        nkit = norm_freq[i]
        inner_sum = 0
        for j in range(len(norm_freq)):
            npit = norm_freq[j]
            dkp = abs(val[i] - val[j])
            inner_sum += npit*dkp
    outer_sum += (nkit**2)*inner_sum
    
    return outer_sum

output_df["Duca_Saving_S1"] = output_df.apply(lambda x: duca_saving(x), axis = 1)

# Drop "income" groupby column
output_df = output_df.drop(columns = ["dkp"], axis = 1)

output_df

,std_dev_age,native_share,education_variability,county,job_variability,frac_employed,median_income,gini_index,Lindqvist_Ostling_S1,Abramowitz_Saunders_S1,Duca_Saving_S1
aplb4d,,,,,,,,,,,
Aberdeen City,15.196623,0.875000,27.5,Aberdeen City,27.5,0.607143,5455.766113,0.519385,11.100974,3.946429,0.001572
Adur; Worthing,21.108135,0.894737,18.5,Adur; Worthing,18.5,0.421053,5003.030029,0.470579,3.528450,2.763158,0.002223
Allerdale; Carlisle,16.277886,0.963303,54.0,Allerdale; Carlisle,54.0,0.605505,6204.619629,0.442821,2.161570,3.247706,0.000839
Alnwick; Berwick; Morpeth; Tynedale,23.060996,1.000000,3.0,Alnwick; Berwick; Morpeth; Tynedale,3.0,0.285714,3715.673340,0.377750,0.809524,3.142857,0.081633
Alyn & Deeside; Delyn; Wrexham Maelor,17.071726,0.975610,61.0,Alyn & Deeside; Delyn; Wrexham Maelor,61.0,0.455285,5108.415039,0.424249,2.808210,3.186992,0.000660
...,...,...,...,...,...,...,...,...,...,...,...
Wirral,19.975800,0.933333,52.0,Wirral,52.0,0.361905,4551.285156,0.563936,6.713919,3.342857,0.000415
Wokingham,15.587291,1.000000,5.0,Wokingham,5.0,0.818182,10648.406250,0.278845,0.890909,2.909091,0.016529
Wolverhampton,17.193862,0.923077,19.0,Wolverhampton,19.0,0.384615,3943.374512,0.465119,5.955466,3.025641,0.023938
Woodspring,20.884911,0.962963,13.0,Woodspring,13.0,0.481481,12391.048828,0.395611,2.122507,2.481481,0.009145
Wycombe,14.807123,0.911765,33.5,Wycombe,33.5,0.514706,8316.907227,0.530993,5.403863,3.029412,0.000884

In [9]:
# Define the dictionary to encode the "aopsocd" column which is Statement 2 (S2)
# S2: "Major public services and industries ought to be in state ownership."

aopsocd_dict = {"Agree":2, "Disagree":4 , "Not agree/disagr": 3 ,"Strongly disagr": 5, 
                "don't know": -1 , "Strongly agree": 1 ,"proxy":-7, "missing or wild": -9, 
                "refused":-2, "inapplicable":-9, "Not agree/disag": 3}

# Create a new column "aopsocd_encoded" in the dataframe by replacing the values with encoded values from the dictionary
df_residence["aopsocd_encoded"] = df_residence["aopsocd"].replace(aopsocd_dict)

# Political polarization measurement by Lindqvist and Ostling (2010)
output_df["Lindqvist_Ostling_S2"] = df_residence.groupby("aplb4d")["aopsocd_encoded"].agg(["var"])

# Create new columns based on absolute sum of encoded values of opinions and counts
output_df["abs_sum"] = df_residence.groupby("aplb4d")["aopsocd_encoded"].apply(lambda x: x.abs().sum())
output_df["counts"] = df_residence.groupby("aplb4d")["aopsocd_encoded"].apply(lambda x: x.count())

# Political polarization measurement by Abramowitz and Saunders (2008)
output_df["Abramowitz_Saunders_S2"] = output_df.apply(lambda x: x["abs_sum"]/x["counts"], axis = 1)

output_df = output_df.drop(columns = ["abs_sum", "counts"], axis = 1)

# Group the dataframe by county and aopsocc_encoded values
output_df["dkp"] = df_residence.groupby("aplb4d")["aopsocd_encoded"]

# Political polarization measurement by Duca and Saving (2016)
def duca_saving(x):
    county_tuple = x["dkp"]
    freq = list(county_tuple[1].value_counts())
    val = list(county_tuple[1].unique())
    norm_freq = [i/sum(freq) for i in freq]
    outer_sum = 0
    for i in range(len(norm_freq)):
        nkit = norm_freq[i]
        inner_sum = 0
        for j in range(len(norm_freq)):
            npit = norm_freq[j]
            dkp = abs(val[i] - val[j])
            inner_sum += npit*dkp
    outer_sum += (nkit**2)*inner_sum
    
    return outer_sum

output_df["Duca_Saving_S2"] = output_df.apply(lambda x: duca_saving(x), axis = 1)

# Drop "income" groupby column
output_df = output_df.drop(columns = ["dkp"], axis = 1)

output_df

,std_dev_age,native_share,education_variability,county,job_variability,frac_employed,median_income,gini_index,Lindqvist_Ostling_S1,Abramowitz_Saunders_S1,Duca_Saving_S1,Lindqvist_Ostling_S2,Abramowitz_Saunders_S2,Duca_Saving_S2
aplb4d,,,,,,,,,,,,,,
Aberdeen City,15.196623,0.875000,27.5,Aberdeen City,27.5,0.607143,5455.766113,0.519385,11.100974,3.946429,0.001572,9.724675,3.142857,0.001526
Adur; Worthing,21.108135,0.894737,18.5,Adur; Worthing,18.5,0.421053,5003.030029,0.470579,3.528450,2.763158,0.002223,4.275960,2.842105,0.001713
Allerdale; Carlisle,16.277886,0.963303,54.0,Allerdale; Carlisle,54.0,0.605505,6204.619629,0.442821,2.161570,3.247706,0.000839,2.273700,2.944954,0.000797
Alnwick; Berwick; Morpeth; Tynedale,23.060996,1.000000,3.0,Alnwick; Berwick; Morpeth; Tynedale,3.0,0.285714,3715.673340,0.377750,0.809524,3.142857,0.081633,2.476190,3.142857,0.037901
Alyn & Deeside; Delyn; Wrexham Maelor,17.071726,0.975610,61.0,Alyn & Deeside; Delyn; Wrexham Maelor,61.0,0.455285,5108.415039,0.424249,2.808210,3.186992,0.000660,2.577102,2.658537,0.000605
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Wirral,19.975800,0.933333,52.0,Wirral,52.0,0.361905,4551.285156,0.563936,6.713919,3.342857,0.000415,6.694689,3.142857,0.001607
Wokingham,15.587291,1.000000,5.0,Wokingham,5.0,0.818182,10648.406250,0.278845,0.890909,2.909091,0.016529,0.963636,2.818182,0.015778
Wolverhampton,17.193862,0.923077,19.0,Wolverhampton,19.0,0.384615,3943.374512,0.465119,5.955466,3.025641,0.023938,6.300945,3.461538,0.025826
Woodspring,20.884911,0.962963,13.0,Woodspring,13.0,0.481481,12391.048828,0.395611,2.122507,2.481481,0.009145,1.256410,3.222222,0.009755
Wycombe,14.807123,0.911765,33.5,Wycombe,33.5,0.514706,8316.907227,0.530993,5.403863,3.029412,0.000884,5.500219,3.308824,0.000588

In [10]:
# Define the dictionary to encode the "aopsocd" column which is Statement 3 (S3)
# S3: "It is the government’s responsibility to provide a job for everyone who wants one."

aopsoce_dict = {"Agree":2, "Disagree":4 , "Not agree/disagr": 3 ,"Strongly disagr": 5, 
                "don't know": -1 , "Strongly agree": 1 ,"proxy":-7, "missing or wild": -9, 
                "refused":-2, "inapplicable":-9, "Not agree/disag": 3}

# Create a new column "aopsocd_encoded" in the dataframe by replacing the values with encoded values from the dictionary
df_residence["aopsoce_encoded"] = df_residence["aopsoce"].replace(aopsoce_dict)

# Political polarization measurement by Lindqvist and Ostling (2010)
output_df["Lindqvist_Ostling_S3"] = df_residence.groupby("aplb4d")["aopsoce_encoded"].agg(["var"])

# Create new columns based on absolute sum of encoded values of opinions and counts
output_df["abs_sum"] = df_residence.groupby("aplb4d")["aopsoce_encoded"].apply(lambda x: x.abs().sum())
output_df["counts"] = df_residence.groupby("aplb4d")["aopsoce_encoded"].apply(lambda x: x.count())

# Political polarization measurement by Abramowitz and Saunders (2008)
output_df["Abramowitz_Saunders_S3"] = output_df.apply(lambda x: x["abs_sum"]/x["counts"], axis = 1)

output_df = output_df.drop(columns = ["abs_sum", "counts"], axis = 1)

# Group the dataframe by county and aopsocc_encoded values
output_df["dkp"] = df_residence.groupby("aplb4d")["aopsoce_encoded"]

# Political polarization measurement by Duca and Saving (2016)
def duca_saving(x):
    county_tuple = x["dkp"]
    freq = list(county_tuple[1].value_counts())
    val = list(county_tuple[1].unique())
    norm_freq = [i/sum(freq) for i in freq]
    outer_sum = 0
    for i in range(len(norm_freq)):
        nkit = norm_freq[i]
        inner_sum = 0
        for j in range(len(norm_freq)):
            npit = norm_freq[j]
            dkp = abs(val[i] - val[j])
            inner_sum += npit*dkp
    outer_sum += (nkit**2)*inner_sum
    
    return outer_sum

output_df["Duca_Saving_S3"] = output_df.apply(lambda x: duca_saving(x), axis = 1)

# Drop "income" groupby column
output_df = output_df.drop(columns = ["dkp"], axis = 1)

output_df

,std_dev_age,native_share,education_variability,county,job_variability,frac_employed,median_income,gini_index,Lindqvist_Ostling_S1,Abramowitz_Saunders_S1,Duca_Saving_S1,Lindqvist_Ostling_S2,Abramowitz_Saunders_S2,Duca_Saving_S2,Lindqvist_Ostling_S3,Abramowitz_Saunders_S3,Duca_Saving_S3
aplb4d,,,,,,,,,,,,,,,,,
Aberdeen City,15.196623,0.875000,27.5,Aberdeen City,27.5,0.607143,5455.766113,0.519385,11.100974,3.946429,0.001572,9.724675,3.142857,0.001526,9.463636,3.000000,0.022208
Adur; Worthing,21.108135,0.894737,18.5,Adur; Worthing,18.5,0.421053,5003.030029,0.470579,3.528450,2.763158,0.002223,4.275960,2.842105,0.001713,4.029161,2.815789,0.002424
Allerdale; Carlisle,16.277886,0.963303,54.0,Allerdale; Carlisle,54.0,0.605505,6204.619629,0.442821,2.161570,3.247706,0.000839,2.273700,2.944954,0.000797,2.053857,2.513761,0.000795
Alnwick; Berwick; Morpeth; Tynedale,23.060996,1.000000,3.0,Alnwick; Berwick; Morpeth; Tynedale,3.0,0.285714,3715.673340,0.377750,0.809524,3.142857,0.081633,2.476190,3.142857,0.037901,1.285714,3.571429,0.029155
Alyn & Deeside; Delyn; Wrexham Maelor,17.071726,0.975610,61.0,Alyn & Deeside; Delyn; Wrexham Maelor,61.0,0.455285,5108.415039,0.424249,2.808210,3.186992,0.000660,2.577102,2.658537,0.000605,2.077702,2.715447,0.000175
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Wirral,19.975800,0.933333,52.0,Wirral,52.0,0.361905,4551.285156,0.563936,6.713919,3.342857,0.000415,6.694689,3.142857,0.001607,6.315385,3.000000,0.001513
Wokingham,15.587291,1.000000,5.0,Wokingham,5.0,0.818182,10648.406250,0.278845,0.890909,2.909091,0.016529,0.963636,2.818182,0.015778,0.818182,2.727273,0.045079
Wolverhampton,17.193862,0.923077,19.0,Wolverhampton,19.0,0.384615,3943.374512,0.465119,5.955466,3.025641,0.023938,6.300945,3.461538,0.025826,6.677463,3.282051,0.006355
Woodspring,20.884911,0.962963,13.0,Woodspring,13.0,0.481481,12391.048828,0.395611,2.122507,2.481481,0.009145,1.256410,3.222222,0.009755,2.054131,3.222222,0.002185
Wycombe,14.807123,0.911765,33.5,Wycombe,33.5,0.514706,8316.907227,0.530993,5.403863,3.029412,0.000884,5.500219,3.308824,0.000588,5.649473,3.308824,0.002328

In [11]:
output_df.reset_index(drop=True, inplace=True)
output_df

,std_dev_age,native_share,education_variability,county,job_variability,frac_employed,median_income,gini_index,Lindqvist_Ostling_S1,Abramowitz_Saunders_S1,Duca_Saving_S1,Lindqvist_Ostling_S2,Abramowitz_Saunders_S2,Duca_Saving_S2,Lindqvist_Ostling_S3,Abramowitz_Saunders_S3,Duca_Saving_S3
0,15.196623,0.875000,27.5,Aberdeen City,27.5,0.607143,5455.766113,0.519385,11.100974,3.946429,0.001572,9.724675,3.142857,0.001526,9.463636,3.000000,0.022208
1,21.108135,0.894737,18.5,Adur; Worthing,18.5,0.421053,5003.030029,0.470579,3.528450,2.763158,0.002223,4.275960,2.842105,0.001713,4.029161,2.815789,0.002424
2,16.277886,0.963303,54.0,Allerdale; Carlisle,54.0,0.605505,6204.619629,0.442821,2.161570,3.247706,0.000839,2.273700,2.944954,0.000797,2.053857,2.513761,0.000795
3,23.060996,1.000000,3.0,Alnwick; Berwick; Morpeth; Tynedale,3.0,0.285714,3715.673340,0.377750,0.809524,3.142857,0.081633,2.476190,3.142857,0.037901,1.285714,3.571429,0.029155
4,17.071726,0.975610,61.0,Alyn & Deeside; Delyn; Wrexham Maelor,61.0,0.455285,5108.415039,0.424249,2.808210,3.186992,0.000660,2.577102,2.658537,0.000605,2.077702,2.715447,0.000175
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
281,19.975800,0.933333,52.0,Wirral,52.0,0.361905,4551.285156,0.563936,6.713919,3.342857,0.000415,6.694689,3.142857,0.001607,6.315385,3.000000,0.001513
282,15.587291,1.000000,5.0,Wokingham,5.0,0.818182,10648.406250,0.278845,0.890909,2.909091,0.016529,0.963636,2.818182,0.015778,0.818182,2.727273,0.045079
283,17.193862,0.923077,19.0,Wolverhampton,19.0,0.384615,3943.374512,0.465119,5.955466,3.025641,0.023938,6.300945,3.461538,0.025826,6.677463,3.282051,0.006355
284,20.884911,0.962963,13.0,Woodspring,13.0,0.481481,12391.048828,0.395611,2.122507,2.481481,0.009145,1.256410,3.222222,0.009755,2.054131,3.222222,0.002185
285,14.807123,0.911765,33.5,Wycombe,33.5,0.514706,8316.907227,0.530993,5.403863,3.029412,0.000884,5.500219,3.308824,0.000588,5.649473,3.308824,0.002328